<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\Subject;
use Illuminate\Database\Seeder;

class DECETCurriculumSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $decet = Course::where('code', 'DECET')->first();

        if (!$decet) {
            $this->command->error('DECET course not found!');
            return;
        }

        $subjects = [
            // YEAR 1 - TERM 1
            [
                'code' => 'CHEM 015',
                'title' => 'Chemistry for Engineers',
                'description' => 'Chemistry for Engineers',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ECEN 101',
                'title' => 'Basic Electronics 1',
                'description' => 'Basic Electronics 1',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ECET 101',
                'title' => 'Consumer Electronics Servicing 1',
                'description' => 'Consumer Electronics Servicing 1',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ENSC 013',
                'title' => 'Engineering Drawing',
                'description' => 'Engineering Drawing',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'GEED 005',
                'title' => 'Purposive Communication/Malayuning Komunikasyon',
                'description' => 'Purposive Communication/Malayuning Komunikasyon',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'GEED 008',
                'title' => 'Ethics/Etika',
                'description' => 'Ethics/Etika',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'MATH 101',
                'title' => 'Calculus 1',
                'description' => 'Calculus 1',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'NSTP 001',
                'title' => 'National Service Training Program 1',
                'description' => 'National Service Training Program 1',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 0,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 1',
                'title' => 'Physical Activity Towards Health and Fitness 1',
                'description' => 'Physical Activity Towards Health and Fitness 1',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => null,
                'coreq' => null,
            ],

            // YEAR 1 - TERM 2
            [
                'code' => 'ECEN 102',
                'title' => 'Basic Electronics 2',
                'description' => 'Basic Electronics 2',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => 'ECEN 101',
                'coreq' => 'ECEN 201',
            ],
            [
                'code' => 'ECEN 201',
                'title' => 'Electronics 1: Electronic Devices and Circuits Theory',
                'description' => 'Electronics 1: Electronic Devices and Circuits Theory',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ECET 102',
                'title' => 'Consumer Electronics Servicing 2',
                'description' => 'Consumer Electronics Servicing 2',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'ECET 101',
                'coreq' => null,
            ],
            [
                'code' => 'ENGL 012',
                'title' => 'Technical Communication',
                'description' => 'Technical Communication',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ENSC 014',
                'title' => 'Computer-Aided Drafting',
                'description' => 'Computer-Aided Drafting',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 3,
                'credit_units' => 1,
                'tuition_hours' => 3,
                'prereq' => 'ENSC 013',
                'coreq' => null,
            ],
            [
                'code' => 'MATH 103',
                'title' => 'Calculus 2',
                'description' => 'Calculus 2',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'MATH 101',
                'coreq' => null,
            ],
            [
                'code' => 'NSTP 002',
                'title' => 'National Service Training Program 2',
                'description' => 'National Service Training Program 2',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 0,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 2',
                'title' => 'Physical Activity Towards Health and Fitness 2',
                'description' => 'Physical Activity Towards Health and Fitness 2',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'PATHFIT 1',
                'coreq' => null,
            ],
            [
                'code' => 'PHYS 013',
                'title' => 'Physics for Engineers (Calculus-based)',
                'description' => 'Physics for Engineers (Calculus-based)',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => 'CHEM 015',
                'coreq' => null,
            ],

            // YEAR 2 - TERM 1
            [
                'code' => 'CMPE 012',
                'title' => 'Computer Programming',
                'description' => 'Computer Programming',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ECEN 202',
                'title' => 'Communications 1: Principles of Communication Systems',
                'description' => 'Communications 1: Principles of Communication Systems',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => 'ECEN 201',
                'coreq' => null,
            ],
            [
                'code' => 'ECEN 204',
                'title' => 'Electronics 2: Electronic Circuit Analysis and Design',
                'description' => 'Electronics 2: Electronic Circuit Analysis and Design',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => 'ECEN 201',
                'coreq' => 'ELEN 013',
            ],
            [
                'code' => 'ECET 201',
                'title' => 'Computer Maintenance and Repair',
                'description' => 'Computer Maintenance and Repair',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'ECEN 102',
                'coreq' => null,
            ],
            [
                'code' => 'ELEN 013',
                'title' => 'Circuits 1',
                'description' => 'Circuits 1',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => 'ECEN 204, PHYS 107',
            ],
            [
                'code' => 'PATHFIT 3',
                'title' => 'Physical Activity Towards Health and Fitness 3',
                'description' => 'Physical Activity Towards Health and Fitness 3',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'PATHFIT 2',
                'coreq' => null,
            ],
            [
                'code' => 'PHYS 107',
                'title' => 'Physics 2',
                'description' => 'Physics 2',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => 'ELEN 013',
            ],
            [
                'code' => 'STAT 012',
                'title' => 'Engineering Data Analysis',
                'description' => 'Engineering Data Analysis',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'MATH 103',
                'coreq' => null,
            ],

            // YEAR 2 - TERM 2
            [
                'code' => 'ECEN 205',
                'title' => 'Digital Electronics 1: Logic Circuits and Switching Theory',
                'description' => 'Digital Electronics 1: Logic Circuits and Switching Theory',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => 'ECEN 201',
                'coreq' => null,
            ],
            [
                'code' => 'ECEN 310',
                'title' => 'Electronics 3: Electronic Systems and Design',
                'description' => 'Electronics 3: Electronic Systems and Design',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => 'ECEN 204',
                'coreq' => null,
            ],
            [
                'code' => 'ECET 202',
                'title' => 'AM/FM Broadcast System and Receivers',
                'description' => 'AM/FM Broadcast System and Receivers',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'ECEN 202',
                'coreq' => 'ECET 203',
            ],
            [
                'code' => 'ECET 203',
                'title' => 'Television Broadcast System and Receivers',
                'description' => 'Television Broadcast System and Receivers',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => 'ECET 202',
            ],
            [
                'code' => 'ECET 204',
                'title' => 'ECET Project Development 1',
                'description' => 'ECET Project Development 1',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'GEED 032',
                'title' => 'Filipinolohiya at Pambansang Kaunlaran',
                'description' => 'Filipinolohiya at Pambansang Kaunlaran',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'MATH 209',
                'title' => 'Differential Equations',
                'description' => 'Differential Equations',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 4',
                'title' => 'Physical Activity Towards Health and Fitness 4',
                'description' => 'Physical Activity Towards Health and Fitness 4',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'PATHFIT 3',
                'coreq' => null,
            ],

            // YEAR 2 - TERM 3 (SUMMER)
            [
                'code' => 'ECET 205',
                'title' => 'Practicum 1 (300 hours)',
                'description' => 'Practicum 1 (300 hours)',
                'year_level' => 2,
                'term' => 3,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => null,
                'coreq' => null,
            ],

            // YEAR 3 - TERM 1
            [
                'code' => 'ECEN 206',
                'title' => 'Communications 2: Modulation & Coding Techniques',
                'description' => 'Communications 2: Modulation & Coding Techniques',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => 'ECEN 202',
                'coreq' => null,
            ],
            [
                'code' => 'ECET 301',
                'title' => 'Mechatronics',
                'description' => 'Mechatronics',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => 'ECEN 102',
                'coreq' => null,
            ],
            [
                'code' => 'ECET 302',
                'title' => 'Industrial Electronics',
                'description' => 'Industrial Electronics',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'ECEN 204',
                'coreq' => null,
            ],
            [
                'code' => 'ECET 303',
                'title' => 'Photovoltaic (PV) Installation Design and Maintenance',
                'description' => 'Photovoltaic (PV) Installation Design and Maintenance',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'ECET 101',
                'coreq' => null,
            ],
            [
                'code' => 'ECET 304',
                'title' => 'ECET Project Development 2',
                'description' => 'ECET Project Development 2',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => 'ECET 204',
                'coreq' => null,
            ],
            [
                'code' => 'ELEN 014',
                'title' => 'Circuits 2',
                'description' => 'Circuits 2',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => 'MATH 209, ELEN 013',
                'coreq' => null,
            ],
            [
                'code' => 'ENSC 027',
                'title' => 'Materials Science & Engineering',
                'description' => 'Materials Science & Engineering',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'CHEM 015',
                'coreq' => null,
            ],
            [
                'code' => 'ENSC 029',
                'title' => 'Technopreneurship 101',
                'description' => 'Technopreneurship 101',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],

            // YEAR 3 - TERM 2
            [
                'code' => 'ECET 305',
                'title' => 'Practicum 2 (300 hours)',
                'description' => 'Practicum 2 (300 hours)',
                'year_level' => 3,
                'term' => 2,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => 'ECET 205',
                'coreq' => null,
            ],
            [
                'code' => 'ECET 306',
                'title' => 'Seminars, Issues and Trends in ECET',
                'description' => 'Seminars, Issues and Trends in ECET',
                'year_level' => 3,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
        ];

        foreach ($subjects as $subjectData) {
            Subject::updateOrCreate(
                [
                    'course_id' => $decet->id,
                    'code' => $subjectData['code'],
                    'year_level' => $subjectData['year_level'],
                    'term' => $subjectData['term'],
                ],
                array_merge(['course_id' => $decet->id], $subjectData)
            );
        }

        $this->command->info('DECET curriculum seeded successfully!');
        $this->command->info('Total subjects: ' . count($subjects));
    }
}
