<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\Subject;
use Illuminate\Database\Seeder;

class DEETCurriculumSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $deet = Course::where('code', 'DEET')->first();

        if (! $deet) {
            $this->command?->error('DEET course not found! Run CourseSeeder first to create it.');
            return;
        }

        // Clear existing DEET subjects to keep curriculum in sync
        Subject::where('course_id', $deet->id)->delete();

        $subjects = [
            // YEAR 1 - TERM 1
            [
                'code' => 'CHEM 015',
                'title' => 'Chemistry for Engineers',
                'description' => 'Chemistry for Engineers',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'EETE 101',
                'title' => 'Basic Electrical Instruments',
                'description' => 'Basic Electrical Instruments',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'EETE 102',
                'title' => 'Philippine Electrical Code',
                'description' => 'Philippine Electrical Code',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ENSC 013',
                'title' => 'Engineering Drawing',
                'description' => 'Engineering Drawing',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'GEED 005',
                'title' => 'Purposive Communication/Malayuning Komunikasyon',
                'description' => 'Purposive Communication/Malayuning Komunikasyon',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'GEED 008',
                'title' => 'Ethics/Etika',
                'description' => 'Ethics/Etika',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'MATH 101',
                'title' => 'Calculus 1',
                'description' => 'Calculus 1',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'NSTP 001',
                'title' => 'National Service Training Program 1',
                'description' => 'National Service Training Program 1',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 0,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 1',
                'title' => 'Physical Activity Towards Health and Fitness 1',
                'description' => 'Physical Activity Towards Health and Fitness 1',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => null,
                'coreq' => null,
            ],

            // YEAR 1 - TERM 2
            [
                'code' => 'EETE 103',
                'title' => 'Electrical Motors and Transformer Rewinding',
                'description' => 'Electrical Motors and Transformer Rewinding',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => 'EETE 101',
                'coreq' => null,
            ],
            [
                'code' => 'EETE 104',
                'title' => 'Preventive Maintenance for Electrical Engineering Technology',
                'description' => 'Preventive Maintenance for Electrical Engineering Technology',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 3,
                'credit_units' => 1,
                'tuition_hours' => 3,
                'prereq' => 'EETE 102',
                'coreq' => 'EETE 103',
            ],
            [
                'code' => 'ELEN 101',
                'title' => 'EE Shop Practice and Electrical Code',
                'description' => 'EE Shop Practice and Electrical Code',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => 'EETE 102, EETE 101',
                'coreq' => null,
            ],
            [
                'code' => 'ENGL 012',
                'title' => 'Technical Communication',
                'description' => 'Technical Communication',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ENSC 014',
                'title' => 'Computer-Aided Drafting',
                'description' => 'Computer-Aided Drafting',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 3,
                'credit_units' => 1,
                'tuition_hours' => 3,
                'prereq' => 'ENSC 013',
                'coreq' => null,
            ],
            [
                'code' => 'ENSC 030',
                'title' => 'Basic Occupational Safety and Health',
                'description' => 'Basic Occupational Safety and Health',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'MATH 103',
                'title' => 'Calculus 2',
                'description' => 'Calculus 2',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'MATH 101',
                'coreq' => 'EETE 104',
            ],
            [
                'code' => 'NSTP 002',
                'title' => 'National Service Training Program 2',
                'description' => 'National Service Training Program 2',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 0,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 2',
                'title' => 'Physical Activity Towards Health and Fitness 2',
                'description' => 'Physical Activity Towards Health and Fitness 2',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'PATHFIT 1',
                'coreq' => null,
            ],
            [
                'code' => 'PHYS 013',
                'title' => 'Physics for Engineers (Calculus-based)',
                'description' => 'Physics for Engineers (Calculus-based)',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => 'MATH 101',
                'coreq' => null,
            ],

            // YEAR 2 - TERM 1
            [
                'code' => 'CMPE 012',
                'title' => 'Computer Programming',
                'description' => 'Computer Programming',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ECEN 015',
                'title' => 'Electromagnetics',
                'description' => 'Electromagnetics',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'PHYS 013',
                'coreq' => null,
            ],
            [
                'code' => 'EETE 201',
                'title' => 'Design, Layout and Estimates',
                'description' => 'Design, Layout and Estimates',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => 'ELEN 101, EETE 102',
                'coreq' => null,
            ],
            [
                'code' => 'ELEN 201',
                'title' => 'Electrical Circuits 1',
                'description' => 'Electrical Circuits 1',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => 'MATH 103, PHYS 013',
                'coreq' => null,
            ],
            [
                'code' => 'ELEN 205',
                'title' => 'EE Laws, Codes and Professional Ethics',
                'description' => 'EE Laws, Codes and Professional Ethics',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'GEED 008',
                'coreq' => null,
            ],
            [
                'code' => 'ENSC 018',
                'title' => 'Engineering Mechanics',
                'description' => 'Engineering Mechanics',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'PHYS 013',
                'coreq' => null,
            ],
            [
                'code' => 'MATH 209',
                'title' => 'Differential Equations',
                'description' => 'Differential Equations',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'MATH 103',
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 3',
                'title' => 'Physical Activity Towards Health and Fitness 3',
                'description' => 'Physical Activity Towards Health and Fitness 3',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'PATHFIT 2',
                'coreq' => null,
            ],
            [
                'code' => 'STAT 012',
                'title' => 'Engineering Data Analysis',
                'description' => 'Engineering Data Analysis',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'MATH 101',
                'coreq' => null,
            ],

            // YEAR 2 - TERM 2
            [
                'code' => 'ECEN 012',
                'title' => 'Electronic Circuits: Devices and Analysis',
                'description' => 'Electronic Circuits: Devices and Analysis',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => 'ELEN 201',
                'coreq' => null,
            ],
            [
                'code' => 'EETE 202',
                'title' => 'EE Technology Project Development 1',
                'description' => 'EE Technology Project Development 1',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'EETE 204',
                'title' => 'Photovoltaic (PV) Installation Design and Maintenance',
                'description' => 'Photovoltaic (PV) Installation Design and Maintenance',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => 'EETE 201, EETE 104',
                'coreq' => null,
            ],
            [
                'code' => 'ELEN 204',
                'title' => 'Electrical Circuits 2',
                'description' => 'Electrical Circuits 2',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => 'ELEN 201',
                'coreq' => null,
            ],
            [
                'code' => 'ELEN 304',
                'title' => 'Electrical Standards and Practices',
                'description' => 'Electrical Standards and Practices',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 3,
                'credit_units' => 1,
                'tuition_hours' => 3,
                'prereq' => 'ELEN 205',
                'coreq' => null,
            ],
            [
                'code' => 'ENSC 021',
                'title' => 'Fundamentals of Deformable Bodies',
                'description' => 'Fundamentals of Deformable Bodies',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'ENSC 018',
                'coreq' => null,
            ],
            [
                'code' => 'ENSC 023',
                'title' => 'Engineering Economics',
                'description' => 'Engineering Economics',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'STAT 012',
                'coreq' => null,
            ],
            [
                'code' => 'GEED 032',
                'title' => 'Filipinolohiya at Pambansang Kaunlaran',
                'description' => 'Filipinolohiya at Pambansang Kaunlaran',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 4',
                'title' => 'Physical Activity Towards Health and Fitness 4',
                'description' => 'Physical Activity Towards Health and Fitness 4',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'PATHFIT 3',
                'coreq' => null,
            ],

            // YEAR 2 - TERM 3 (SUMMER)
            [
                'code' => 'EETE 203',
                'title' => 'Practicum 1 (300 hours)',
                'description' => 'Practicum 1 (300 hours)',
                'year_level' => 2,
                'term' => 3,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => null,
                'coreq' => null,
            ],

            // YEAR 3 - TERM 1
            [
                'code' => 'ECEN 013',
                'title' => 'Industrial Electronics',
                'description' => 'Industrial Electronics',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => 'ECEN 012',
                'coreq' => null,
            ],
            [
                'code' => 'EETE 301',
                'title' => 'Illumination Engineering Design',
                'description' => 'Illumination Engineering Design',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'EETE 201',
                'coreq' => null,
            ],
            [
                'code' => 'EETE 302',
                'title' => 'Electrical Engineering Technology Project Development 2',
                'description' => 'Electrical Engineering Technology Project Development 2',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => 'EETE 202',
                'coreq' => null,
            ],
            [
                'code' => 'ELEN 202',
                'title' => 'Mechatronics',
                'description' => 'Mechatronics',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'CMPE 012, ECEN 012',
                'coreq' => null,
            ],
            [
                'code' => 'ELEN 303',
                'title' => 'Electrical Apparatus and Devices',
                'description' => 'Electrical Apparatus and Devices',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'ELEN 204',
                'coreq' => null,
            ],
            [
                'code' => 'ELEN 411',
                'title' => 'Management of Engineering Projects',
                'description' => 'Management of Engineering Projects',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'ENSC 023',
                'coreq' => null,
            ],
            [
                'code' => 'ENSC 026',
                'title' => 'Environmental Science and Engineering',
                'description' => 'Environmental Science and Engineering',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ENSC 028',
                'title' => 'Materials Science and Engineering',
                'description' => 'Materials Science and Engineering',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'CHEM 015, ENSC 021',
                'coreq' => null,
            ],
            [
                'code' => 'ENSC 029',
                'title' => 'Technopreneurship 101',
                'description' => 'Technopreneurship 101',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],

            // YEAR 3 - TERM 2
            [
                'code' => 'EETE 303',
                'title' => 'Practicum 2 (300 hours)',
                'description' => 'Practicum 2 (300 hours)',
                'year_level' => 3,
                'term' => 2,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => 'EETE 203',
                'coreq' => null,
            ],
            [
                'code' => 'EETE 304',
                'title' => 'Seminars on Issues and Trends in EET',
                'description' => 'Seminars on Issues and Trends in EET',
                'year_level' => 3,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
        ];

        foreach ($subjects as $data) {
            Subject::updateOrCreate(
                [
                    'course_id' => $deet->id,
                    'code' => $data['code'],
                    'year_level' => $data['year_level'],
                    'term' => $data['term'],
                ],
                array_merge(['course_id' => $deet->id], $data)
            );
        }

        $this->command?->info('DEET curriculum seeded successfully!');
        $this->command?->info('Total subjects: ' . count($subjects));
    }
}

