<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\Subject;
use Illuminate\Database\Seeder;

class DITCurriculumSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Find DIT course
        $dit = Course::where('code', 'DIT')->first();

        if (! $dit) {
            $this->command?->error('DIT course not found! Run CourseSeeder first to create it.');
            return;
        }

        // Clear existing DIT subjects to keep curriculum in sync
        Subject::where('course_id', $dit->id)->delete();

        $subjects = [
            // YEAR 1 - TERM 1
            [
                'code' => 'COMP 001',
                'title' => 'Introduction to Computing',
                'description' => 'Introduction to Computing',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'COMP 002',
                'title' => 'Computer Programming 1',
                'description' => 'Computer Programming 1',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'GEED 004',
                'title' => 'Mathematics in the Modern World/ Matematika sa Makabagong Daigdig',
                'description' => 'Mathematics in the Modern World/ Matematika sa Makabagong Daigdig',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'GEED 005',
                'title' => 'Purposive Communication/ Malayuning Komunikasyon',
                'description' => 'Purposive Communication/ Malayuning Komunikasyon',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ITEC 101',
                'title' => 'Keyboarding and Documents Processing with Laboratory',
                'description' => 'Keyboarding and Documents Processing with Laboratory',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ITEC 102',
                'title' => 'Basic Computer Hardware Servicing',
                'description' => 'Basic Computer Hardware Servicing',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'NSTP 001',
                'title' => 'National Service Training Program 1',
                'description' => 'National Service Training Program 1',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 0,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 1',
                'title' => 'Physical Activity Towards Health and Fitness 1',
                'description' => 'Physical Activity Towards Health and Fitness 1',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => null,
                'coreq' => null,
            ],

            // YEAR 1 - TERM 2
            [
                'code' => 'COMP 003',
                'title' => 'Computer Programming 2',
                'description' => 'Computer Programming 2',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'COMP 002',
                'coreq' => null,
            ],
            [
                'code' => 'COMP 004',
                'title' => 'Discrete Structures 1',
                'description' => 'Discrete Structures 1',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'GEED 004',
                'coreq' => null,
            ],
            [
                'code' => 'COMP 024',
                'title' => 'Technopreneurship',
                'description' => 'Technopreneurship',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'GEED 001',
                'title' => 'Understanding the Self/ Pag-unawa sa Sarili',
                'description' => 'Understanding the Self/ Pag-unawa sa Sarili',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'GEED 007',
                'title' => 'Science, Technology and Society/ Agham, Teknolohiya, at Lipunan',
                'description' => 'Science, Technology and Society/ Agham, Teknolohiya, at Lipunan',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ITEC 103',
                'title' => 'Hardware/ Software Installation and Maintenance',
                'description' => 'Hardware/ Software Installation and Maintenance',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'ITEC 102',
                'coreq' => null,
            ],
            [
                'code' => 'ITEC 104',
                'title' => 'Basic Electronics',
                'description' => 'Basic Electronics',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'NSTP 002',
                'title' => 'National Service Training Program 2',
                'description' => 'National Service Training Program 2',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 0,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 2',
                'title' => 'Physical Activity Towards Health and Fitness 2',
                'description' => 'Physical Activity Towards Health and Fitness 2',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'PATHFIT 1',
                'coreq' => null,
            ],

            // YEAR 2 - TERM 1
            [
                'code' => 'COMP 006',
                'title' => 'Data Structures and Algorithms',
                'description' => 'Data Structures and Algorithms',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'COMP 007',
                'title' => 'Operating Systems',
                'description' => 'Operating Systems',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'COMP 001',
                'coreq' => null,
            ],
            [
                'code' => 'COMP 008',
                'title' => 'Data Communications and Networking',
                'description' => 'Data Communications and Networking',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'COMP 023',
                'title' => 'Social and Professional Issues in Computing',
                'description' => 'Social and Professional Issues in Computing',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'INTE 201',
                'title' => 'Programming 3 (Structured Programming)',
                'description' => 'Programming 3 (Structured Programming)',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'COMP 003',
                'coreq' => null,
            ],
            [
                'code' => 'INTE 202',
                'title' => 'Integrative Programming and Technologies 1',
                'description' => 'Integrative Programming and Technologies 1',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 3',
                'title' => 'Physical Activity Towards Health and Fitness 3',
                'description' => 'Physical Activity Towards Health and Fitness 3',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'PATHFIT 2',
                'coreq' => null,
            ],

            // YEAR 2 - TERM 2
            [
                'code' => 'COMP 009',
                'title' => 'Object Oriented Programming',
                'description' => 'Object Oriented Programming',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'COMP 003',
                'coreq' => null,
            ],
            [
                'code' => 'COMP 010',
                'title' => 'Information Management',
                'description' => 'Information Management',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'INTE 201',
                'coreq' => null,
            ],
            [
                'code' => 'COMP 012',
                'title' => 'Network Administration',
                'description' => 'Network Administration',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'COMP 008',
                'coreq' => null,
            ],
            [
                'code' => 'COMP 013',
                'title' => 'Human Computer Interaction',
                'description' => 'Human Computer Interaction',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'COMP 014',
                'title' => 'Quantitative Methods with Modeling and Simulation',
                'description' => 'Quantitative Methods with Modeling and Simulation',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'COMP 016',
                'title' => 'Web Development',
                'description' => 'Web Development',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'INTE 202',
                'coreq' => null,
            ],
            [
                'code' => 'COMP 030',
                'title' => 'Business Intelligence',
                'description' => 'Business Intelligence',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'INTE 403',
                'title' => 'Systems Administration and Maintenance',
                'description' => 'Systems Administration and Maintenance',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => null,
                'coreq' => null,
            ],

            // YEAR 2 - TERM 3 (SUMMER)
            [
                'code' => 'ITEC 201',
                'title' => 'Practicum 1 (Junior Programmer 1 / Junior Programmer 2 - 300 hours)',
                'description' => 'Practicum 1 (Junior Programmer 1 / Junior Programmer 2 - 300 hours)',
                'year_level' => 2,
                'term' => 3,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => null,
                'coreq' => null,
            ],

            // YEAR 3 - TERM 1
            [
                'code' => 'COMP 015',
                'title' => 'Fundamentals of Research',
                'description' => 'Fundamentals of Research',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'COMP 017',
                'title' => 'Multimedia',
                'description' => 'Multimedia',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'COMP 016',
                'coreq' => null,
            ],
            [
                'code' => 'COMP 018',
                'title' => 'Database Administration',
                'description' => 'Database Administration',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'COMP 019',
                'title' => 'Applications Development and Emerging Technologies',
                'description' => 'Applications Development and Emerging Technologies',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'COMP 025',
                'title' => 'Project Management',
                'description' => 'Project Management',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'COMP 027',
                'title' => 'Mobile Application Development (SMP PLUS)',
                'description' => 'Mobile Application Development (SMP PLUS)',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'INTE 351',
                'title' => 'Systems Analysis and Design',
                'description' => 'Systems Analysis and Design',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ITEC 301',
                'title' => 'Advance Programming',
                'description' => 'Advance Programming',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'COMP 003',
                'coreq' => null,
            ],

            // YEAR 3 - TERM 2
            [
                'code' => 'ITEC 302',
                'title' => 'Capstone',
                'description' => 'Capstone',
                'year_level' => 3,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ITEC 303',
                'title' => 'Practicum 2 (Computer Programming Specialist - 300 hours)',
                'description' => 'Practicum 2 (Computer Programming Specialist - 300 hours)',
                'year_level' => 3,
                'term' => 2,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ITEC 304',
                'title' => 'Seminar on Issues and Trends in Information Technology',
                'description' => 'Seminar on Issues and Trends in Information Technology',
                'year_level' => 3,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
        ];

        foreach ($subjects as $data) {
            Subject::updateOrCreate(
                [
                    'course_id' => $dit->id,
                    'code' => $data['code'],
                    'year_level' => $data['year_level'],
                    'term' => $data['term'],
                ],
                array_merge(['course_id' => $dit->id], $data)
            );
        }

        $this->command?->info('DIT curriculum seeded successfully!');
        $this->command?->info('Total subjects: ' . count($subjects));
    }
}

