<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\Subject;
use Illuminate\Database\Seeder;

class DMETCurriculumSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dmet = Course::where('code', 'DMET')->first();

        if (! $dmet) {
            $this->command?->error('DMET course not found! Run CourseSeeder first to create it.');
            return;
        }

        // Clear existing DMET subjects to keep curriculum in sync
        Subject::where('course_id', $dmet->id)->delete();

        $subjects = [
            // YEAR 1 - TERM 1
            [
                'code' => 'CHEM 015',
                'title' => 'Chemistry for Engineers',
                'description' => 'Chemistry for Engineers',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ENSC 013',
                'title' => 'Engineering Drawing',
                'description' => 'Engineering Drawing',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'GEED 008',
                'title' => 'Ethics/Etika',
                'description' => 'Ethics/Etika',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'MATH 101',
                'title' => 'Calculus 1',
                'description' => 'Calculus 1',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'MEEN 101',
                'title' => 'Mechanical Engineering Orientation',
                'description' => 'Mechanical Engineering Orientation',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 1,
                'lab_hours' => 0,
                'credit_units' => 1,
                'tuition_hours' => 1,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'MEEN 202',
                'title' => 'Workshop Theory and Practice',
                'description' => 'Workshop Theory and Practice',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'METE 101',
                'title' => 'Basic Automotive',
                'description' => 'Basic Automotive',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 1',
                'title' => 'Physical Activity Towards Health and Fitness 1',
                'description' => 'Physical Activity Towards Health and Fitness 1',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'NSTP 001',
                'title' => 'National Service Training Program 1',
                'description' => 'National Service Training Program 1',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 0,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'MEEN 414',
                'title' => 'ME Laws, Ethics, Contracts, Codes and Standards',
                'description' => 'ME Laws, Ethics, Contracts, Codes and Standards',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => null,
                'coreq' => null,
            ],

            // YEAR 1 - TERM 2
            [
                'code' => 'ENGL 012',
                'title' => 'Technical Communication',
                'description' => 'Technical Communication',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ENSC 014',
                'title' => 'Computer-Aided Drafting',
                'description' => 'Computer-Aided Drafting',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 3,
                'credit_units' => 1,
                'tuition_hours' => 3,
                'prereq' => 'ENSC 013',
                'coreq' => null,
            ],
            [
                'code' => 'MATH 103',
                'title' => 'Calculus 2',
                'description' => 'Calculus 2',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'MATH 101',
                'coreq' => 'PHYS 013',
            ],
            [
                'code' => 'ENSC 030',
                'title' => 'Basic Occupational Safety and Health',
                'description' => 'Basic Occupational Safety and Health',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'MEEN 205',
                'title' => 'Machine Shop Theory',
                'description' => 'Machine Shop Theory',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => 'MEEN 202',
                'coreq' => null,
            ],
            [
                'code' => 'METE 103',
                'title' => 'RAC Servicing 1',
                'description' => 'RAC Servicing 1',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 3,
                'credit_units' => 1,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'METE 102',
                'title' => 'Advanced Automotive',
                'description' => 'Advanced Automotive',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => 'METE 101',
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 2',
                'title' => 'Physical Activity Towards Health and Fitness 2',
                'description' => 'Physical Activity Towards Health and Fitness 2',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'PATHFIT 1',
                'coreq' => null,
            ],
            [
                'code' => 'NSTP 002',
                'title' => 'National Service Training Program 2',
                'description' => 'National Service Training Program 2',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 0,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'PHYS 013',
                'title' => 'Physics for Engineers (Calculus-based)',
                'description' => 'Physics for Engineers (Calculus-based)',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => 'MATH 101',
                'coreq' => 'MATH 103',
            ],

            // YEAR 2 - TERM 1
            [
                'code' => 'ENSC 016',
                'title' => 'Statics of Rigid Bodies',
                'description' => 'Statics of Rigid Bodies',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'PHYS 013, MATH 103',
                'coreq' => null,
            ],
            [
                'code' => 'GEED 032',
                'title' => 'Filipinolohiya at Pambansang Kaunlaran',
                'description' => 'Filipinolohiya at Pambansang Kaunlaran',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'MATH 209',
                'title' => 'Differential Equations',
                'description' => 'Differential Equations',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'MATH 103',
                'coreq' => null,
            ],
            [
                'code' => 'MEEN 201',
                'title' => 'Thermodynamics 1',
                'description' => 'Thermodynamics 1',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'MATH 103, PHYS 013',
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 3',
                'title' => 'Physical Activity Towards Health and Fitness 3',
                'description' => 'Physical Activity Towards Health and Fitness 3',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'PATHFIT 2',
                'coreq' => null,
            ],
            [
                'code' => 'ELEN 016',
                'title' => 'Basic Electrical Engineering',
                'description' => 'Basic Electrical Engineering',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'MATH 103, PHYS 013',
                'coreq' => null,
            ],
            [
                'code' => 'CMPE 011',
                'title' => 'Computer Fundamentals and Programming',
                'description' => 'Computer Fundamentals and Programming',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'METE 202',
                'title' => 'Auto Engine Rebuilding 1',
                'description' => 'Auto Engine Rebuilding 1',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => 'METE 102',
                'coreq' => null,
            ],
            [
                'code' => 'METE 201',
                'title' => 'CAD/CAM Operation 1 (2D)',
                'description' => 'CAD/CAM Operation 1 (2D)',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 3,
                'credit_units' => 1,
                'tuition_hours' => 3,
                'prereq' => 'ENSC 013, ENSC 014',
                'coreq' => null,
            ],
            [
                'code' => 'METE 203',
                'title' => 'RAC Servicing 2 (NC II)',
                'description' => 'RAC Servicing 2 (NC II)',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 3,
                'credit_units' => 1,
                'tuition_hours' => 3,
                'prereq' => 'METE 103',
                'coreq' => null,
            ],

            // YEAR 2 - TERM 2
            [
                'code' => 'ENSC 017',
                'title' => 'Dynamics of Rigid Bodies',
                'description' => 'Dynamics of Rigid Bodies',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'ENSC 016',
                'coreq' => null,
            ],
            [
                'code' => 'METE 204',
                'title' => 'Preventive Maintenance for ME',
                'description' => 'Preventive Maintenance for ME',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 3,
                'credit_units' => 1,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'METE 208',
                'title' => 'MET Project Development 1',
                'description' => 'MET Project Development 1',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 4',
                'title' => 'Physical Activity Towards Health and Fitness 4',
                'description' => 'Physical Activity Towards Health and Fitness 4',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'PATHFIT 3',
                'coreq' => null,
            ],
            [
                'code' => 'STAT 012',
                'title' => 'Engineering Data Analysis',
                'description' => 'Engineering Data Analysis',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'MATH 101',
                'coreq' => null,
            ],
            [
                'code' => 'METE 207',
                'title' => 'Auto Engine Rebuilding 2 (NC II)',
                'description' => 'Auto Engine Rebuilding 2 (NC II)',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => 'METE 202',
                'coreq' => null,
            ],
            [
                'code' => 'ECEN 016',
                'title' => 'Basic Electronics',
                'description' => 'Basic Electronics',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'ELEN 016',
                'coreq' => null,
            ],
            [
                'code' => 'METE 205',
                'title' => 'CAD/CAM Operation 2 3D (NC III)',
                'description' => 'CAD/CAM Operation 2 3D (NC III)',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 3,
                'credit_units' => 1,
                'tuition_hours' => 3,
                'prereq' => 'METE 201',
                'coreq' => null,
            ],
            [
                'code' => 'METE 206',
                'title' => 'Shielded Metal Arc Welding 1',
                'description' => 'Shielded Metal Arc Welding 1',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'MEEN 204',
                'title' => 'Thermodynamics 2',
                'description' => 'Thermodynamics 2',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'MEEN 201',
                'coreq' => null,
            ],

            // YEAR 2 - TERM 3 (SUMMER)
            [
                'code' => 'METE 209',
                'title' => 'Practicum 1 (300 hours)',
                'description' => 'Practicum 1 (300 hours)',
                'year_level' => 2,
                'term' => 3,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => null,
                'coreq' => null,
            ],

            // YEAR 3 - TERM 1
            [
                'code' => 'ENSC 024',
                'title' => 'Engineering Management',
                'description' => 'Engineering Management',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ENSC 029',
                'title' => 'Technopreneurship 101',
                'description' => 'Technopreneurship 101',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'GEED 005',
                'title' => 'Purposive Communication/Malayuning Komunikasyon',
                'description' => 'Purposive Communication/Malayuning Komunikasyon',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'MEEN 301',
                'title' => 'DC and AC Machinery',
                'description' => 'DC and AC Machinery',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => 'ECEN 016',
                'coreq' => null,
            ],
            [
                'code' => 'METE 301',
                'title' => 'Fundamentals of Driving and Practice',
                'description' => 'Fundamentals of Driving and Practice',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 3,
                'credit_units' => 1,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'METE 302',
                'title' => 'MET Project Development 2',
                'description' => 'MET Project Development 2',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => 'METE 208',
                'coreq' => null,
            ],
            [
                'code' => 'METE 303',
                'title' => 'Gas Metal Arc Welding',
                'description' => 'Gas Metal Arc Welding',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => 'METE 304',
                'coreq' => null,
            ],
            [
                'code' => 'METE 304',
                'title' => 'Shielded Metal Arc Welding 2',
                'description' => 'Shielded Metal Arc Welding 2',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => 'METE 303',
                'coreq' => null,
            ],
            [
                'code' => 'METE 305',
                'title' => 'Combustion Engineering',
                'description' => 'Combustion Engineering',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'MEEN 204',
                'coreq' => null,
            ],

            // YEAR 3 - TERM 2
            [
                'code' => 'METE 307',
                'title' => 'Practicum 2 (300 hours)',
                'description' => 'Practicum 2 (300 hours)',
                'year_level' => 3,
                'term' => 2,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => 'METE 209',
                'coreq' => null,
            ],
            [
                'code' => 'METE 306',
                'title' => 'Seminars on Issues and Trends in MET',
                'description' => 'Seminars on Issues and Trends in MET',
                'year_level' => 3,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
        ];

        foreach ($subjects as $data) {
            Subject::updateOrCreate(
                [
                    'course_id' => $dmet->id,
                    'code' => $data['code'],
                    'year_level' => $data['year_level'],
                    'term' => $data['term'],
                ],
                array_merge(['course_id' => $dmet->id], $data)
            );
        }

        $this->command?->info('DMET curriculum seeded successfully!');
        $this->command?->info('Total subjects: ' . count($subjects));
    }
}

