<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\Subject;
use Illuminate\Database\Seeder;

class DOMTCurriculumSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Find DOMT course
        $domt = Course::where('code', 'DOMT')->first();

        if (! $domt) {
            $this->command?->error('DOMT course not found! Run CourseSeeder first to create it.');
            return;
        }

        // Clear existing DOMT subjects to keep curriculum in sync
        Subject::where('course_id', $domt->id)->delete();

        $subjects = [
            // YEAR 1 - TERM 1
            [
                'code' => 'GEED 001',
                'title' => 'Understanding the Self/Pag-unawa sa Sarili',
                'description' => 'Understanding the Self/Pag-unawa sa Sarili',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'GEED 004',
                'title' => 'Mathematics in the Modern World/Matematika sa Makabagong Daigdig',
                'description' => 'Mathematics in the Modern World/Matematika sa Makabagong Daigdig',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'NSTP 001',
                'title' => 'National Service Training Program 1',
                'description' => 'National Service Training Program 1',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 0,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'OFAD 101',
                'title' => 'Keyboard and Documents Processing',
                'description' => 'Keyboard and Documents Processing',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'OFAD 102',
                'title' => 'Foundation of Shorthand',
                'description' => 'Foundation of Shorthand',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'OFAD 103',
                'title' => 'Administrative Office Procedures and Records Management',
                'description' => 'Administrative Office Procedures and Records Management',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 1',
                'title' => 'Physical Activity Towards Health and Fitness 1',
                'description' => 'Physical Activity Towards Health and Fitness 1',
                'year_level' => 1,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => null,
                'coreq' => null,
            ],

            // YEAR 1 - TERM 2
            [
                'code' => 'COMP 101',
                'title' => 'Integrated Software Application',
                'description' => 'Integrated Software Application',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'GEED 005',
                'title' => 'Purposive Communication/Malayuning Komunikasyon',
                'description' => 'Purposive Communication/Malayuning Komunikasyon',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'GEED 008',
                'title' => 'Ethics/Etika',
                'description' => 'Ethics/Etika',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'NSTP 002',
                'title' => 'National Service Training Program 2',
                'description' => 'National Service Training Program 2',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 0,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'OFAD 104',
                'title' => 'Advanced Shorthand',
                'description' => 'Advanced Shorthand',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => 'OFAD 102',
                'coreq' => null,
            ],
            [
                'code' => 'OFAD 201',
                'title' => 'Personal and Professional Development',
                'description' => 'Personal and Professional Development',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => 'OFAD 103',
                'coreq' => null,
            ],
            [
                'code' => 'OMTE 101',
                'title' => 'Advanced Keyboard and Documents Processing with Laboratory',
                'description' => 'Advanced Keyboard and Documents Processing with Laboratory',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => 'OFAD 101',
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 2',
                'title' => 'Physical Activity Towards Health and Fitness 2',
                'description' => 'Physical Activity Towards Health and Fitness 2',
                'year_level' => 1,
                'term' => 2,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'PATHFIT 1',
                'coreq' => null,
            ],

            // YEAR 2 - TERM 1
            [
                'code' => 'OMTE 102',
                'title' => 'Accounting Principles',
                'description' => 'Accounting Principles',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ENGL 017',
                'title' => 'Business Report Writing',
                'description' => 'Business Report Writing',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'ENTR 101',
                'title' => 'Entrepreneurial Behavior',
                'description' => 'Entrepreneurial Behavior',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'OFAD 361',
                'title' => 'Legal Terminology with Transcription for Court Stenographers and Legal Office Associates',
                'description' => 'Legal Terminology with Transcription for Court Stenographers and Legal Office Associates',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'OFAD 351',
                'title' => 'Legal Office Procedures',
                'description' => 'Legal Office Procedures',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'LAW 015',
                'title' => 'Business Law (Obligations and Contracts)',
                'description' => 'Business Law (Obligations and Contracts)',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'OFAD 105',
                'title' => 'Principles of Public and Customer Relations',
                'description' => 'Principles of Public and Customer Relations',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'PATHFIT 3',
                'title' => 'Physical Activity Towards Health and Fitness 3',
                'description' => 'Physical Activity Towards Health and Fitness 3',
                'year_level' => 2,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 0,
                'credit_units' => 2,
                'tuition_hours' => 2,
                'prereq' => 'PATHFIT 2',
                'coreq' => null,
            ],

            // YEAR 2 - TERM 2
            [
                'code' => 'ACCO 017',
                'title' => 'Corporate Accounting',
                'description' => 'Corporate Accounting',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'OMTE 201',
                'title' => 'Legal Transcription',
                'description' => 'Legal Transcription',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'OFAD 205',
                'title' => 'Internet Research for Business',
                'description' => 'Internet Research for Business',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'OFAD 203',
                'title' => 'Transcription and Speedbuilding with Laboratory',
                'description' => 'Transcription and Speedbuilding with Laboratory',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 3,
                'lab_hours' => 3,
                'credit_units' => 4,
                'tuition_hours' => 6,
                'prereq' => 'OMTE 101, OFAD 104',
                'coreq' => null,
            ],
            [
                'code' => 'OFAD 302',
                'title' => 'Machine Shorthand 1',
                'description' => 'Machine Shorthand 1',
                'year_level' => 2,
                'term' => 2,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => null,
                'coreq' => null,
            ],

            // YEAR 2 - TERM 3 (SUMMER)
            [
                'code' => 'OMTE 203',
                'title' => 'Practicum 1 (Office Management 300 hrs.)',
                'description' => 'Practicum 1 (Office Management 300 hrs.)',
                'year_level' => 2,
                'term' => 3,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => null,
                'coreq' => null,
            ],

            // YEAR 3 - TERM 1
            [
                'code' => 'COMP 106',
                'title' => 'Introduction to Database Management System',
                'description' => 'Introduction to Database Management System',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 2,
                'lab_hours' => 3,
                'credit_units' => 3,
                'tuition_hours' => 5,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'OFAD 371',
                'title' => 'Filipino Stenography',
                'description' => 'Filipino Stenography',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'OFAD 202',
                'title' => 'Web Design for Business',
                'description' => 'Web Design for Business',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'OFAD 301',
                'title' => 'Events Management',
                'description' => 'Events Management',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 3,
                'lab_hours' => 0,
                'credit_units' => 3,
                'tuition_hours' => 3,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'OFAD 451',
                'title' => 'Machine Shorthand 2',
                'description' => 'Machine Shorthand 2',
                'year_level' => 3,
                'term' => 1,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => null,
                'coreq' => null,
            ],

            // YEAR 3 - TERM 2
            [
                'code' => 'OMTE 301',
                'title' => 'Practicum 2 (Legal Office Management 300 hrs)',
                'description' => 'Practicum 2 (Legal Office Management 300 hrs)',
                'year_level' => 3,
                'term' => 2,
                'lec_hours' => 1,
                'lab_hours' => 6,
                'credit_units' => 3,
                'tuition_hours' => 7,
                'prereq' => null,
                'coreq' => null,
            ],
            [
                'code' => 'OMTE 303',
                'title' => 'Seminar on Issues and Trends in Office Management Technology',
                'description' => 'Seminar on Issues and Trends in Office Management Technology',
                'year_level' => 3,
                'term' => 2,
                'lec_hours' => 0,
                'lab_hours' => 6,
                'credit_units' => 2,
                'tuition_hours' => 6,
                'prereq' => null,
                'coreq' => null,
            ],
        ];

        foreach ($subjects as $data) {
            Subject::updateOrCreate(
                [
                    'course_id' => $domt->id,
                    'code' => $data['code'],
                    'year_level' => $data['year_level'],
                    'term' => $data['term'],
                ],
                array_merge(['course_id' => $domt->id], $data)
            );
        }

        $this->command?->info('DOMT curriculum seeded successfully!');
        $this->command?->info('Total subjects: ' . count($subjects));
    }
}

